### ISSUE TITLE
Loading Hang-Ups (Tags Only?)

### ISSUE THREAD

**Issue by minixmousy** [blackjackkent/RPThreadTrackerV3.FrontEnd#1]
tracker username: minniemouse
blog url in question: animusdeviance

with the new character system, i decided to take the old character tags i had for my smaller multimuse and remove them. each time, the system seemed to take longer to load than with anything else.

**Comment by blackjackkent** [comment]
Hmm. Thanks for the report! Can you be more specific about what is taking a long time to load? The tags are taking a long time to load when editing a thread? Or something else?

**Comment by minixmousy** [comment]
it was the site as a whole, honestly. upon playing with the tracker more, it just seemed to take a while to load anyway, which might be due to the server it's on or the fact that i'd had so many threads tracked. XD
this "issue" can probably be ignored. :P apologies for that!

**Comment by blackjackkent** [comment]
No worries! Thanks for the heads up regardless!

**Comment by lovethecoat51** [comment]
I had a similar problem - I was doing the exact same thing, but when i finished taking all the tags off, there were no options left in the drop down tag menu, but it still wasn't loading any threads. I can only assume it's because it was looking for a tag that was no longer there and it also wouldn't let me unselect the tag. If that makes sense??

**Comment by blackjackkent** [comment]
@lovethecoat51 Hmm, that sounds like a separate issue and I'll need to get some clarification from you -- could you go ahead and create a separate ticket using the "New Issue" button so we don't spam the OP on this issue? Thanks!
