### ISSUE TITLE
Tag filter remains selected if last thread with that tag has tag removed

### ISSUE THREAD

**Issue by lovethecoat51** [blackjackkent/RPThreadTrackerV3.FrontEnd#11]
I was switching the tags to characters (which is a GREAT new feature, I love it). So as long as I have a thread with the tag, it's fine.
![01](https://user-images.githubusercontent.com/41085634/42537842-fa23914a-848d-11e8-9eb2-2876d0a8ed88.PNG)
Like this. But as I deleted the tags, there were no more threads with any tag at all, and I was unable to de-select any tag in the drop down menu, so I was given a screen like this:
![03](https://user-images.githubusercontent.com/41085634/42537886-16caa6a8-848e-11e8-9fa8-e6b3881f4288.PNG)
I ended up refreshing the page and everything was fine, but I feel like that shouldn't happen.

**Comment by blackjackkent** [comment]
Aha, okay, I see what you mean.

I'm probably going to put this lower on the priority list to fix, just because it's something of an edge case and can be resolved by a reload, and also because I'm gonna have to think a bit about the best way to address it. But it's a good point and I'll definitely keep it on the task list.

Thank you very much for the heads up!

**Comment by lovethecoat51** [comment]
Totally understandable!

And I'm LOVING the new site btw!

**Comment by blackjackkent** [comment]
Thank you! :) I'm glad to hear it!
