### ISSUE TITLE
Change Email is Greyed Out and Unselectable

### ISSUE THREAD

**Issue by minixmousy** [blackjackkent/RPThreadTrackerV3.FrontEnd#20]
i'm not sure if it's something you intended or not, but the option to change the email is greyed out and i can't select it. seeing the option made me really excited bc i'd used an old as heck email for the tracker but i can't update it to one i use frequently.
![image](https://user-images.githubusercontent.com/41029884/42668028-5fd5159c-8603-11e8-907f-0430acfc0c4e.png)

**Comment by blackjackkent** [comment]
This is intentional, yes -- the email management stuff is going to be an update made after the new design is deployed, because it's going to require more work on my part and I want to get the site out. I'll add an indication somewhere that this is a future feature coming.

That said -- if you want to change the email for your account, please send me an email at rpthreadtracker@gmail.com from your old and new email addresses and I can make the update myself in the database. :)
