### ISSUE TITLE
Visual Fix: Manage Characters

### ISSUE THREAD

**Issue by pixiegaga** [blackjackkent/RPThreadTrackerV3.FrontEnd#23]
Username: pixiegaga

I was moving the options on the 'manage characters' page. I currently have 3 pages with 10 rows each, when I tried to put the option of '20 rows' the new rows appeared but with no information on them, and if I tried to change the page it went back to default (10 rows).

**Comment by blackjackkent** [comment]
Very good catch! Not sure what's going on here but there's definitely something wrong with the pagination behavior on that table. (It doesn't seem to be happening with the threads tables which is doubly weird since they use almost the same code.)

I'll look into this and update when I've pushed a fix! Thank you. :)

**Comment by blackjackkent** [comment]
OK, figured out the issue; this behavior should be resolved now! :) Thanks for catching this.
