### ISSUE TITLE
Last Post Date in Archive?

### ISSUE THREAD

**Issue by purpledragon42** [blackjackkent/RPThreadTrackerV3.FrontEnd#26]
So this actually ties in a little to the comment I made about 'Last Post Dates' in the thread about Public Views.  Because of how I use the Archive feature, I find it very helpful to be able to sort by the 'Last Post Date'.  I have a lot of partners who are on the slower side.  And by slower I mean it can take them several months to get me a reply.  After 6 months, I put presumably dead threads in the Archive.  However, because a lot of my partners _are_ slow, once a month or so I check my archive using 'Last Post Date' to see if anyone has replied.  It's a small thing, but it makes it easier for me to look over everything at a glance to see if I owe anyone unexpected.  ^_^

**Comment by blackjackkent** [comment]
I've had a couple of messages about this; my original intention was to reduce the amount of time it takes to load the archive (because not getting info from Tumblr's servers) but it seems like a lot of people used the recent post information on that even if the threads were archived. So I will work on re-implementing the original behavior for that table. :)

Thanks!

**Comment by blackjackkent** [comment]
I have updated the Archived Threads page so that it also retrieves status information from Tumblr. I believe everything should be solid, but this was reasonably large rework of that chunk of the site, so please let me know how things look and if anything sticks out to you as odd.

Thanks so much! :)
