### ISSUE TITLE
moving archived threads to queue freezes / doesn't work

### ISSUE THREAD

**Issue by fibifibita** [blackjackkent/RPThreadTrackerV3.FrontEnd#4]
fibifibita
175662097671 (one of them)
i tried using the bulk action "mark selected threads queued" to move items to the queue and it thinks, refreshes the page, gives the green pop ups saying the threads have been updated but they continue to show in archived.
If I move them back to your/turn my turn it works. 
I tried the same from "your turn" and "their turn" and works fine.

**Comment by blackjackkent** [comment]
Aha. Good catch -- I think I know what the issue is here. Will work on an update and let you know when it's finished. :) Thank you!

**Comment by blackjackkent** [comment]
OK, so basically -- the idea was never to have it be possible to mark threads queued from the archive screen which is why you're seeing weird behavior; you'll notice there's no button for it on the individual table rows. You're supposed to only be able to unarchive or delete an archived thread, and queueing is for threads that are currently active. So I've removed that option from the dropdown menu on the archived threads table.

You should still see it correctly on the Your Turn and Their Turn thread tables, though, and be able to mark threads queued from there without a problem.

Let me know if this all seems to be working correctly now. Thanks so much for catching this!

**Comment by fibifibita** [comment]
Thanks for the clarification! Queued isn't showing as an option anymore on archive and works just fine in your/their turn. Thanks!

**Comment by blackjackkent** [comment]
Perfect. Thanks so much!
