### ISSUE TITLE
Public View Creation Issue

### ISSUE THREAD

**Issue by purpledragon42** [blackjackkent/RPThreadTrackerV3.FrontEnd#40]
So, I've created a few Public Views in the past with little problem, but I've tried several times tonight to create one, and I'm getting an error message.

Here's the view I'm trying to create:
![image](https://user-images.githubusercontent.com/41037873/45535398-f4e5b280-b7c3-11e8-9a9f-b71f9603d437.png)

And here's the error I'm receiving:
![image](https://user-images.githubusercontent.com/41037873/45535424-0e86fa00-b7c4-11e8-9365-055469d6fd69.png)

I was trying to create something that would show all the threads I owe, including ones that might've been replied to after I archived them.  Any ideas about what might be going on?  Or more likely, what I'm doing wrong?  ^_^;

**Comment by blackjackkent** [comment]
Aha, I know why this is happening. "allthreads" is a restricted value for the URL slug; it can't be used because users might potentially still have their public view URLs from the current version of the site, which could use that slug and I am (for the moment) allowing those URLs to continue working with the new version. I'll work on adding an indicator to the site to note when a particular slug is invalid.

Thank you for catching this! :)

**Comment by blackjackkent** [comment]
Hey. :) I've updated the "Create Public View" modal; you should see a suitable bit of feedback when you enter an invalid slug. Let me know how it behaves for you! Thanks. :)
