### ISSUE TITLE
Exporting Threads

### ISSUE THREAD

**Issue by purpledragon42** [blackjackkent/RPThreadTrackerV3.FrontEnd#41]
I was trying to export my threads and had a couple of issues.

First, the toggle button for 'Include Characters on Hiatus' wouldn't toggle to yes.

Second, when I tried to export, both with and without archived threads, it only exported one (the first character) of my 20+ connected blogs.

**Comment by blackjackkent** [comment]
Those are both definitely significant bugs. :O Lemme work on this and get back to you; thanks for catching this!

**Comment by blackjackkent** [comment]
Hmm. I'm having trouble reproducing the issue with only exporting one character's threads. Would you feel comfortable giving me your login info by email so I can try exporting your characters specifically?

**Comment by purpledragon42** [comment]
Actually... that's my bad.  ^_^;  I just opened up the file again and realized that it's exporting each character into a different sheet in Excel.  For some reason, I was expecting them to all be on the same sheet, so I wasn't paying attention.  Everything looks good.  :)  Thank you!

**Comment by purpledragon42** [comment]
Just a quick tag-on to this thread since my new question also deals with exporting.  Is there any way that the 'Last Post Date' could be exported, too?  Or if we could maybe pick and choose more of the details that get exported?  Thanks so much!  :)

**Comment by blackjackkent** [comment]
(Apologies for the delay in responding -- have been out of town).

The export tool was originally conceived as a way to download a full list of your threads during a period when the Tracker isn't performing its usual function for some reason (i.e. during a Tumblr outage where that information wouldn't be available anyway), so it's intended to be a pretty lightweight process. Adding calls to Tumblr would make the export process more resource intensive and take a lot longer and wouldn't be relevant a lot of the time anyway since you would have the same information available on the tracker thread tables. 

I'll add an FAQ item to clarify this but for right now it's not an aspect I'm interested in adding to the feature. Thank you for mentioning it though! I appreciate all ideas. :)

**Comment by blackjackkent** [comment]
Also, the issue with the  hiatused blogs toggle should be resolved now; let me know if everything looks okay! :)
