### ISSUE TITLE
Managing Characters Pages

### ISSUE THREAD

**Issue by glcryxdays** [blackjackkent/RPThreadTrackerV3.FrontEnd#44]
I was wondering if there was a way to refresh the page on the 'manage characters' section when adding a new character so it doesn't take me back to page one again. With the amount of characters I have, and when I add more, if I'm on a far page, it's a little tiring to have to keep finding the page I was at to redo it again when I add more.

I really appreciate everything you're doing, thank you.

**Comment by blackjackkent** [comment]
Hey! This is definitely a good idea; I already have on my to-do list an fix that will allow updating threads without refreshing the whole table, and I will update that to include the character table as well. (This might not be added till after the site release since it's not a breaking bug and we're in the final stretch but it's definitely one of my priorities for soon after.)
